# generated by datamodel-codegen:
#   filename:  base_config.yaml
#   timestamp: 2025-11-24T22:42:43+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Rpc(BaseModel):
    port: int


class Minner(BaseModel):
    coinbase_address: str
    op_return_data: str


class PeerNode(BaseModel):
    host: str
    port: int


class P2p(BaseModel):
    data_dir: str
    listen_port: int
    coinbase_address: str
    peer_nodes: List[PeerNode]


class Model(BaseModel):
    enable_rpc: bool = Field(..., alias='enable-rpc')
    enable_indexer: bool = Field(..., alias='enable-indexer')
    enable_minner: bool = Field(..., alias='enable-minner')
    data_dir: str
    log_dir: str
    rpc: Rpc
    minner: Minner
    p2p: P2p
